### ISSUE TITLE
Update and clean introduction

### ISSUE THREAD

**Issue by csmagnano** [ccb-hms/osca-workbench#1]
Update vignette into more fleshed-out lesson for [#episodes/intro-sce.Rmd](https://github.com/ccb-hms/osca-workbench/blob/main/episodes/intro-sce.Rmd).

This includes:

- Adding questions, objectives, and key points to the lesson
- Adjusting the teaching and exercises times (in minutes) at the top of the file
- Suppressing unwanted warnings or other output
- Adding additional explanatory text where needed to improve the overall flow of the lesson
- Any other changes you think might improve the lesson

**Comment by lgeistlinger** [comment]
This looks pretty good to me now, feel free to close this issue when ready @csmagnano
