### ISSUE TITLE
Update package list on setup page

### ISSUE THREAD

**Issue by csmagnano** [ccb-hms/osca-workbench#11]
On the [setup page](https://github.com/ccb-hms/osca-workbench/blob/main/learners/setup.md) the final instruction is for participants to install a list of packages in preparation for the workshop:

```r
install.packages(c("BiocManager", "remotes"))
BiocManager::install(c("tidyverse", "SummarizedExperiment", "hexbin",
                       "patchwork", "gridExtra", "lubridate"))
```

We should update this list of packages to be those needed for the single cell lessons, especially since some of the data packages can take awhile to install.

**Comment by lgeistlinger** [comment]
Resolved in 30f96adef31646589e5da4016f71be68e3fe3684
