### ISSUE TITLE
Update and clean introduction EDA and QC lesson

### ISSUE THREAD

**Issue by csmagnano** [ccb-hms/osca-workbench#2]
Update vignette into more fleshed-out lesson for [#episodes/eda_qc.Rmd](https://github.com/ccb-hms/osca-workbench/blob/main/episodes/eda_qc.Rmd).

This includes:

- Adding questions, objectives, and key points to the lesson
- Adjusting the teaching and exercises times (in minutes) at the top of the file
- Suppressing unwanted warnings or other output
- Adding additional explanatory text where needed to improve the overall flow of the lesson
- Any other changes you think might improve the lesson

**Comment by lgeistlinger** [comment]
Except of the issue with the references #8 this looks also pretty much ready to go for me
