### ISSUE TITLE
Update and clean hca lesson

### ISSUE THREAD

**Issue by csmagnano** [ccb-hms/osca-workbench#6]
Update vignette into more fleshed-out lesson for [#episodes/hca.Rmd](https://ccb-hms.github.io/osca-workbench/hca.Rmd).

This includes:

- Adding questions, objectives, and key points to the lesson
- Adjusting the teaching and exercises times (in minutes) at the top of the file
- Suppressing unwanted warnings or other output
- Adding additional explanatory text where needed to improve the overall flow of the lesson
- Any other changes you think might improve the lesson

**Comment by lgeistlinger** [comment]
finalized in [71c5690](https://github.com/ccb-hms/osca-workbench/commit/71c5690c9fbc42f636e1b5d75499d52d020ee886)
