### ISSUE TITLE
Manage citations and references

### ISSUE THREAD

**Issue by csmagnano** [ccb-hms/osca-workbench#8]
The original tutorial used a `.bib` bibliography and included references throughout. I'm not sure how R Markdown bibliographies will interact with workbench. We should:

1. Determine if bibliographies are supported in workbench, and manage the citations if they are. 
2. If they are not, decide how we want to handle citations.

**Comment by lgeistlinger** [comment]
From the education meeting:

In the Collaborative Lesson Development Training curriculum, we are using footnotes and a separate Bibliography listing in the References page. See https://carpentries.github.io/lesson-development-training/lesson-design.html#a-lesson-design-process for an example.
